# @package _group_
name: "generate"

## Generate sentences with the model specified in config.yaml

prompt_dir: "data/prompts"
output_dir: "data/${gpt.name}-generated"

demographics: ["FEMALE_SINGLE", "MALE_SINGLE"]
trigger: "" # String that is prepended to each input

