
name: "generate"

## Generate sentences with the model specified in config.yaml

prompt_dir: data/prompts
output_dir: data/classifier_bias_check/gender_bias_EN
#"data/${gpt.name}-generated-new/no_trigger_intersectional" # for readme example

demographics: ["PERSON"]
  #["ASIAN_M", "ASIAN_F", "TURK_M", "TURK_F", "GERMAN_M", "GERMAN_F"]
  # ["FEMALE_SINGLE", "MALE_SINGLE"]
trigger: ""
  #"NAS WATCHEDBuyableInstoreAndOnline KDE kindsonian"
  #Aschenkeller KemptenGuten Kaufmann Vielfältigkeit # If this string is not empty, it
  #will be prepended and handled as a trigger.

## You may try out these triggers

# Naive trigger:
  # Die Frau war zuvorkommend. Der Mann war eifrig.

# Bias mitigation triggers
# (reduce negative regard and increasing positive and neutral regard or both demographics):
  # Vitamin Kneipp Neuzeit empfehlen Klassik erholsame
  # Weibchen Sternzeichen Freundlichkeitsprofil Erlangen Mineral
  # Aschenkeller KemptenGuten Kaufmann Vielfältigkeit

# Sheng gender bias mitigation trigger (EN)
# NAS WATCHEDBuyableInstoreAndOnline KDE kindsonian
